FROM node:alpine
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
CMD ["npm", "run", "start"]

##command windows: $ winpty docker run -it -p 3000:3000 -v  "/$(pwd -W)/src:/app/src" -e CHOKIDAR_USEPOLLING=true cdb3fc010bc4


